name: habits_repository
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3+1
  equatable: ^1.0.2
