name: habit_tracker
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  line_icons: ^0.2.0
  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3+1
  equatable: ^1.0.2
  flutter_bloc: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


flutter:


  uses-material-design: true

  assets:
    - assets/